name: tensorflow-demo
version: 1
summary: TensorFlow Demo
description: TensorFlow Image Recognition Demo in Qt
confinement: strict

apps:
  label-image:
    command: label-image
    plugs: [unity7, camera, opengl, network, network-bind, x11]

parts:
  qt:
    plugin: nil
    stage-packages:
      - qmlscene
      - qt5-default
      - qml-module-qtmultimedia
      - qtchooser
      - qtbase5-dev
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
      - qtdeclarative5-dev
      - gstreamer1.0-plugins-good
      - gstreamer1.0-x
#    after: [qt5conf]
  common:
    plugin: dump
    source: data
  model:
    plugin: dump
    source: https://storage.googleapis.com/download.tensorflow.org/models/inception_dec_2015.zip
    organize:
        imagenet_comp_graph_label_strings.txt: model/imagenet_comp_graph_label_strings.txt
        tensorflow_inception_graph.pb: model/tensorflow_inception_graph.pb
        LICENSE: model/LICENSE
